# DevOps Taskmaster - Deployment Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-taskmaster
  namespace: webapp
  labels:
    app: devops-taskmaster
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-taskmaster
  template:
    metadata:
      labels:
        app: devops-taskmaster
    spec:
      containers:
      - name: devops-taskmaster
        # This matches the ECR/DockerHub repository you configured
        image: jonathan661/devops-taskmaster:latest 
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"   
