apiVersion: v1
kind: Service
metadata:
  name: devops-taskmaster-service
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: devops-taskmaster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
