apiVersion: v2
name: devops-taskmaster
description: A Helm chart for the Java Taskmaster Microservice
type: application

# This is the version of the chart itself
version: 2.1.0-stable

# This is the version of your Java application
appVersion: "1.0.0"
